# Generated by Django 3.1.3 on 2020-11-11 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polymail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
    ]
